# Generated by Django 4.0 on 2022-09-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tutor',
            unique_together=set(),
        ),
    ]
